name: "bi-dt"
services:
  app:
    image: dhonanhibatullah/bi-digital-twin-app:1.0.1-dev
    ports:
      - "8080:8080"
    environment:
      APP_HOST: 0.0.0.0
      APP_PORT: 8080
      TOKEN_ISSUER: BengkelInovasiDev
      TOKEN_PRIVATE_KEY: # FILL THIS: can be anything
      TOKEN_EXPIRATION: 12
      DB_USERNAME: bi-digital-twin
      DB_PASSWORD: # FILL THIS: same as POSTGRES_PASSWORD
      DB_HOST: postgres-db
      DB_PORT: 5432
      DB_NAME: bi-digital-twin
      DB_TIMEOUT_MS: 5000
      MQTT_BROKER: tcp://mqtt-broker:1883
      MQTT_CLIENT_ID: bi-dt-mqtt-server
      MQTT_USERNAME: # FILL THIS: same as prompted
      MQTT_PASSWORD: # FILL THIS: same as prompted
    volumes:
      - app-logs:/app/logs
    depends_on:
      postgres-db:
        condition: service_healthy
      mqtt-broker:
        condition: service_started
    networks:
      - app-net

  postgres-db:
    image: timescale/timescaledb-ha:pg16.10-ts2.23.0
    restart: unless-stopped
    environment:
      POSTGRES_USER: bi-digital-twin
      POSTGRES_PASSWORD: # FILL THIS: same as DB_PASSWORD
      POSTGRES_DB: bi-digital-twin
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-net

  mqtt-broker:
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    user: "1883:1883"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  postgres-data:
  app-logs:
